/* =============================================================
   SYAKILLA JUICE — SITE CONTENT (edit file ini saja)
   Semua teks, menu, harga, review, footer ada di sini.
   ============================================================= */
const SITE = {
  brand: { name: "Syakilla ", accent: "Juice" },

  nav: [
    { label: "Menu", href: "/" },
    { label: "Belanja", href: "/belanja" },
    { label: "Tentang", href: "/tentang" },
    { label: "Bantuan", href: "/bantuan" },
    { label: "Blog", href: "/blog" },
  ],

  hero: {
    image: "hero",
    // Video asli proses bikin jus (bukan AI). Ganti URL .mp4 di sini kalau perlu.
    videoUrls: [
      "https://cdn.pixabay.com/video/2021/07/24/82602-580137800_large.mp4",
      "https://cdn.pixabay.com/video/2023/02/16/150882-799711525_large.mp4",
      "https://cdn.pixabay.com/video/2021/01/15/62083-502737742_large.mp4",
    ],
    eyebrow: "Segar Tiap Hari dari Batuphat",
    titleHtml: "Minuman segar, <em>fresh</em>.",
    text: "Alpukat kocok, squash, sampai es teh kekinian. Dibuat fresh tiap pesanan. Pesan online, tinggal ambil sendiri atau diantar ke sekitar Batuphat.",
    primaryCta: { label: "Lihat Menu", href: "#collection" },
    secondaryCta: { label: "Cerita Kami", href: "/tentang" },
  },

  // icon = nama ikon SVG (lihat components/Icons.js): leaf, drop, shield, wa
  features: [
    { icon: "leaf", title: "Bahan Asli", text: "Buah & bahan pilihan" },
    { icon: "drop", title: "Selalu Fresh", text: "Dibuat per pesanan" },
    { icon: "shield", title: "Higienis", text: "Bersih & terjaga" },
    { icon: "wa", title: "Pesan di sini", text: "Cepat & gampang" },
  ],

  collection: {
    eyebrow: "Menu Favorit",
    title: "Menu Andalan",
  },

  // Urutan kategori di halaman Belanja (accordion tutup-buka)
  categories: [
    "Alpukat Kocok",
    "Squash",
    "Tea Series",
    "Milkshake Series",
    "Milky Series",
  ],

  products: [
    // ---------- ALPUKAT KOCOK (ukuran kecil Rp 6.000) ----------
    {
      id: "ak_ori",
      name: "Alpukat Original",
      cat: "Alpukat Kocok",
      img: "ak_ori",
      price: 9000,
      desc: "Alpukat kocok murni, creamy tanpa tambahan. Ukuran kecil Rp 6.000.",
      tag: "",
      stars: 5,
      featured: true,
    },
    {
      id: "ak_coklat",
      name: "Alpukat Coklat",
      cat: "Alpukat Kocok",
      img: "ak_coklat",
      price: 12000,
      desc: "Alpukat kocok + susu + coklat. Ukuran kecil Rp 6.000.",
      tag: "",
      stars: 5,
    },
    {
      id: "ak_keju",
      name: "Alpukat Keju",
      cat: "Alpukat Kocok",
      img: "ak_keju",
      price: 12000,
      desc: "Alpukat kocok + susu + keju parut. Ukuran kecil Rp 6.000.",
      tag: "",
      stars: 5,
    },
    {
      id: "ak_milo",
      name: "Alpukat Milo",
      cat: "Alpukat Kocok",
      img: "ak_milo",
      price: 12000,
      desc: "Alpukat kocok + susu + milo. Ukuran kecil Rp 6.000.",
      tag: "",
      stars: 5,
    },
    {
      id: "ak_oreo",
      name: "Alpukat Oreo",
      cat: "Alpukat Kocok",
      img: "ak_oreo",
      price: 12000,
      desc: "Alpukat kocok + susu + oreo. Ukuran kecil Rp 6.000.",
      tag: "",
      stars: 5,
    },
    {
      id: "ak_special",
      name: "Special Alpukat",
      cat: "Alpukat Kocok",
      img: "ak_special",
      price: 15000,
      desc: "Alpukat kocok + susu + alpukat potong + topping coklat/keju. Ukuran kecil Rp 6.000.",
      tag: "Terlaris",
      stars: 5,
      featured: true,
    },
    {
      id: "ak_glaze",
      name: "Alpukat Glaze",
      cat: "Alpukat Kocok",
      img: "ak_glaze",
      price: 14000,
      desc: "Alpukat kocok + susu + glaze + topping keju/milo/oreo. Ukuran kecil Rp 6.000.",
      tag: "",
      stars: 5,
    },
    {
      id: "ak_yakult",
      name: "Alpukat Yakult",
      cat: "Alpukat Kocok",
      img: "ak_yakult",
      price: 12000,
      desc: "Alpukat kocok + susu + yakult. Ukuran kecil Rp 6.000.",
      tag: "",
      stars: 4,
    },
    {
      id: "ak_nutella",
      name: "Alpukat Nutella",
      cat: "Alpukat Kocok",
      img: "ak_nutella",
      price: 15000,
      desc: "Alpukat kocok nutella + susu + alpukat potong. Ukuran kecil Rp 6.000.",
      tag: "",
      stars: 5,
    },

    // ---------- SQUASH (Besar Rp 8.000 / Kecil Rp 6.000) ----------
    {
      id: "sq_blue",
      name: "Blue Squash",
      cat: "Squash",
      img: "sq_blue",
      price: 8000,
      desc: "Soda biru segar dengan es. Besar Rp 8.000, kecil Rp 6.000.",
      tag: "Segar",
      stars: 4,
    },
    {
      id: "sq_strawberry",
      name: "Strawberry Squash",
      cat: "Squash",
      img: "sq_strawberry",
      price: 8000,
      desc: "Soda strawberry asam manis. Besar Rp 8.000, kecil Rp 6.000.",
      tag: "Segar",
      stars: 5,
      featured: true,
    },
    {
      id: "sq_melon",
      name: "Melon Squash",
      cat: "Squash",
      img: "sq_melon",
      price: 8000,
      desc: "Soda melon manis lembut. Besar Rp 8.000, kecil Rp 6.000.",
      tag: "",
      stars: 4,
    },
    {
      id: "sq_jeruk",
      name: "Jeruk Squash",
      cat: "Squash",
      img: "sq_jeruk",
      price: 8000,
      desc: "Soda jeruk seger dan wangi. Besar Rp 8.000, kecil Rp 6.000.",
      tag: "",
      stars: 5,
    },
    {
      id: "sq_blackcurrant",
      name: "Blackcurrant Squash",
      cat: "Squash",
      img: "sq_blackcurrant",
      price: 8000,
      desc: "Soda blackcurrant manis segar. Besar Rp 8.000, kecil Rp 6.000.",
      tag: "",
      stars: 4,
    },
    {
      id: "sq_lemon",
      name: "Lemon Squash",
      cat: "Squash",
      img: "sq_lemon",
      price: 8000,
      desc: "Soda lemon asam segar. Besar Rp 8.000, kecil Rp 6.000.",
      tag: "",
      stars: 5,
    },
    {
      id: "sq_apel",
      name: "Apel Squash",
      cat: "Squash",
      img: "sq_apel",
      price: 8000,
      desc: "Soda apel manis renyah. Besar Rp 8.000, kecil Rp 6.000.",
      tag: "",
      stars: 4,
    },

    // ---------- TEA SERIES (Es Teh) ----------
    {
      id: "tea_original",
      name: "Original Tea",
      cat: "Tea Series",
      img: "tea_original",
      price: 5000,
      desc: "Tea premium + gula. Es teh klasik yang bikin nagih.",
      tag: "Termurah",
      stars: 5,
      featured: true,
    },
    {
      id: "tea_lychee",
      name: "Lychee Tea",
      cat: "Tea Series",
      img: "tea_lychee",
      price: 7000,
      desc: "Tea premium + gula + syrup leci.",
      tag: "",
      stars: 5,
    },
    {
      id: "tea_lemon",
      name: "Lemon Tea",
      cat: "Tea Series",
      img: "tea_lemon",
      price: 6000,
      desc: "Tea premium + gula + lemon segar.",
      tag: "",
      stars: 5,
    },
    {
      id: "tea_moca",
      name: "Moca Tea",
      cat: "Tea Series",
      img: "tea_moca",
      price: 7000,
      desc: "Tea premium + gula + syrup moca.",
      tag: "",
      stars: 4,
    },
    {
      id: "tea_yakult",
      name: "Yakult Tea",
      cat: "Tea Series",
      img: "tea_yakult",
      price: 8000,
      desc: "Tea premium + gula + yakult.",
      tag: "",
      stars: 5,
    },
    {
      id: "tea_milo",
      name: "Milo Tea",
      cat: "Tea Series",
      img: "tea_milo",
      price: 7000,
      desc: "Tea premium + gula + milo.",
      tag: "",
      stars: 4,
    },

    // ---------- MILKSHAKE SERIES ----------
    {
      id: "ms_original",
      name: "Original Milk Shake",
      cat: "Milkshake Series",
      img: "ms_original",
      price: 7000,
      desc: "UHT + SKM. Milkshake lembut original.",
      tag: "",
      stars: 4,
    },
    {
      id: "ms_chocolate",
      name: "Chocolate Milk Shake",
      cat: "Milkshake Series",
      img: "ms_chocolate",
      price: 8000,
      desc: "UHT + SKM + bubuk choco.",
      tag: "Favorit",
      stars: 5,
      featured: true,
    },
    {
      id: "ms_chocobar",
      name: "Choco Bar Milk Shake",
      cat: "Milkshake Series",
      img: "ms_chocobar",
      price: 8000,
      desc: "UHT + SKM + bubuk choco bar.",
      tag: "",
      stars: 5,
    },
    {
      id: "ms_chocoqueen",
      name: "Choco Queen Milk Shake",
      cat: "Milkshake Series",
      img: "ms_chocoqueen",
      price: 8000,
      desc: "UHT + SKM + bubuk choco queen.",
      tag: "",
      stars: 5,
    },
    {
      id: "ms_chococrumb",
      name: "Choco Crumb Milk Shake",
      cat: "Milkshake Series",
      img: "ms_chococrumb",
      price: 8000,
      desc: "UHT + SKM + choco crumb.",
      tag: "",
      stars: 5,
    },
    {
      id: "ms_chococheese",
      name: "Choco Cheese Milk Shake",
      cat: "Milkshake Series",
      img: "ms_chococheese",
      price: 8000,
      desc: "UHT + SKM + choco cheese.",
      tag: "",
      stars: 5,
    },
    {
      id: "ms_greentea",
      name: "Green Tea Milk Shake",
      cat: "Milkshake Series",
      img: "ms_greentea",
      price: 8000,
      desc: "UHT + SKM + green tea.",
      tag: "",
      stars: 4,
    },
    {
      id: "ms_strawberry",
      name: "Strawberry Milk Shake",
      cat: "Milkshake Series",
      img: "ms_strawberry",
      price: 8000,
      desc: "UHT + SKM + bubuk strawberry.",
      tag: "",
      stars: 5,
    },
    {
      id: "ms_redvelvet",
      name: "Red Velvet Milk Shake",
      cat: "Milkshake Series",
      img: "ms_redvelvet",
      price: 8000,
      desc: "UHT + SKM + bubuk red velvet.",
      tag: "",
      stars: 5,
    },
    {
      id: "ms_tiramisu",
      name: "Tiramisu Milk Shake",
      cat: "Milkshake Series",
      img: "ms_tiramisu",
      price: 8000,
      desc: "UHT + SKM + bubuk tiramisu.",
      tag: "",
      stars: 4,
    },
    {
      id: "ms_thaitea",
      name: "Thai Tea Milk Shake",
      cat: "Milkshake Series",
      img: "ms_thaitea",
      price: 8000,
      desc: "UHT + SKM + bubuk thai tea.",
      tag: "",
      stars: 5,
    },
    {
      id: "ms_taro",
      name: "Taro Milk Shake",
      cat: "Milkshake Series",
      img: "ms_taro",
      price: 8000,
      desc: "UHT + SKM + bubuk taro.",
      tag: "",
      stars: 5,
    },

    // ---------- MILKY SERIES ----------
    {
      id: "mk_mangga",
      name: "Mangga Milk",
      cat: "Milky Series",
      img: "mk_mangga",
      price: 10000,
      desc: "UHT + oreo + bubuk mangga.",
      tag: "Baru",
      stars: 5,
      featured: true,
    },
    {
      id: "mk_grape",
      name: "Grape Milk",
      cat: "Milky Series",
      img: "mk_grape",
      price: 10000,
      desc: "UHT + oreo + bubuk grape.",
      tag: "",
      stars: 4,
    },
    {
      id: "mk_bluevanila",
      name: "Blue Vanila Milk",
      cat: "Milky Series",
      img: "mk_bluevanila",
      price: 10000,
      desc: "UHT + oreo + bubuk blue vanila.",
      tag: "",
      stars: 4,
    },
    {
      id: "mk_chocobanana",
      name: "Choco Banana Milk",
      cat: "Milky Series",
      img: "mk_chocobanana",
      price: 10000,
      desc: "UHT + oreo + bubuk choco banana.",
      tag: "",
      stars: 5,
    },
  ],

  craft: {
    image: "craft",
    eyebrow: "Standar Batuphat",
    title: "Bahan asli, dibuat fresh tiap pesanan.",
    paragraphs: [
      "Kami mulai dari satu prinsip sederhana: pakai bahan asli dan bikin fresh saat pesananmu masuk. Alpukat dipilih matang, teh diseduh pas, dan semua diracik dengan takaran yang konsisten.",
      "Hasilnya rasa yang jujur dan bikin balik lagi, dengan harga yang ramah buat tiap hari.",
    ],
    stats: [
      { n: "5", l: "Kategori menu" },
      { n: "4.9\u2605", l: "Rating pelanggan" },
      { n: "09\u201322", l: "Jam buka (WIB)" },
    ],
  },

  reviews: {
    eyebrow: "Kata Pelanggan",
    title: "4.9 / 5 dari 1.200+ pelanggan",
    items: [
      {
        stars: 5,
        text: "Special Alpukatnya juara! Creamy banget dan topping-nya melimpah. Langganan tiap minggu.",
        avatar: "R",
        name: "Rina A.",
        role: "Batuphat",
      },
      {
        stars: 5,
        text: "Es tehnya seger, squash-nya juga mantap buat siang hari. Pesan lewat WA gampang banget.",
        avatar: "D",
        name: "Dedi P.",
        role: "Pelanggan",
      },
      {
        stars: 5,
        text: "Harga ramah tapi rasa nggak murahan. Milkshake coklatnya favorit anak-anak di rumah.",
        avatar: "S",
        name: "Sari W.",
        role: "Ibu rumah tangga",
      },
    ],
  },

  footer: {
    about:
      "Alpukat kocok, squash, dan es teh kekinian. Dibuat fresh tiap hari di Batuphat, Lhokseumawe.",
    // icon = nama ikon SVG: facebook, instagram, whatsapp
    socials: [
      { icon: "facebook", href: "#" },
      { icon: "instagram", href: "#" },
      { icon: "whatsapp", href: "#" },
    ],
    columns: [
      {
        title: "Menu",
        links: [
          { label: "Alpukat Kocok", href: "/belanja" },
          { label: "Squash", href: "/belanja" },
          { label: "Tea Series", href: "/belanja" },
          { label: "Milkshake Series", href: "/belanja" },
          { label: "Milky Series", href: "/belanja" },
        ],
      },
      {
        title: "Info",
        links: [
          { label: "Tentang Kami", href: "/tentang" },
          { label: "Lokasi", href: "/tentang#lokasi" },
          { label: "Jam Buka", href: "/tentang#lokasi" },
        ],
      },
      {
        title: "Bantuan",
        links: [
          { label: "Cara Pesan", href: "/bantuan#cara-pesan" },
          { label: "Pengantaran", href: "/bantuan#pengantaran" },
        ],
      },
    ],
    copyright: "\u00a9 2026 Syakilla Juice. Segar tiap hari.",
  },

  blog: {
    eyebrow: "Blog Syakilla",
    title: "Cerita, Tips & Kabar Segar",
    intro:
      "Serba-serbi minuman segar, bahan pilihan, dan tips biar harimu makin fresh bareng Syakilla Juice.",
    posts: [
      {
        id: "alpukat-nagih",
        img: "ak_special",
        category: "Menu",
        date: "12 Juli 2026",
        readTime: "4 menit baca",
        author: "Tim Syakilla",
        title: "5 Alasan Alpukat Kocok Bikin Nagih",
        excerpt:
          "Dari tekstur creamy sampai topping yang melimpah, ini rahasia kenapa Special Alpukat jadi menu paling dicari pelanggan.",
      },
      {
        id: "squash-vs-teh",
        img: "sq_strawberry",
        category: "Tips",
        date: "5 Juli 2026",
        readTime: "3 menit baca",
        author: "Tim Syakilla",
        title: "Squash vs Es Teh: Mana Teman Siang Terbaik?",
        excerpt:
          "Cuaca Batuphat lagi terik? Kami bandingkan squash soda yang menyegarkan dengan es teh klasik biar kamu gampang milih.",
      },
      {
        id: "milkshake-lembut",
        img: "ms_chocolate",
        category: "Resep",
        date: "28 Juni 2026",
        readTime: "5 menit baca",
        author: "Barista Syakilla",
        title: "Rahasia Milkshake Lembut ala Syakilla",
        excerpt:
          "Perpaduan UHT dan susu kental manis dengan takaran pas bikin milkshake kami lembut sempurna. Intip triknya di sini.",
      },
      {
        id: "fresh-tiap-pesanan",
        img: "craft",
        category: "Cerita",
        date: "20 Juni 2026",
        readTime: "4 menit baca",
        author: "Tim Syakilla",
        title: "Kenapa Fresh Tiap Pesanan Itu Penting",
        excerpt:
          "Kami tidak menyetok minuman jadi. Setiap gelas diracik saat pesananmu masuk supaya rasa dan kesegarannya selalu terjaga.",
      },
      {
        id: "milky-series-baru",
        img: "mk_mangga",
        category: "Menu Baru",
        date: "14 Juni 2026",
        readTime: "3 menit baca",
        author: "Tim Syakilla",
        title: "Milky Series yang Wajib Kamu Coba",
        excerpt:
          "Mangga Milk, Grape Milk, sampai Choco Banana. Deretan menu Milky Series terbaru kami yang creamy dan kekinian.",
      },
      {
        id: "simpan-buah-segar",
        img: "tea_lychee",
        category: "Tips",
        date: "6 Juni 2026",
        readTime: "4 menit baca",
        author: "Tim Syakilla",
        title: "Cara Simpan Buah biar Tetap Segar",
        excerpt:
          "Buah adalah bintang utama tiap gelas. Ini cara kami memilih dan menyimpan buah supaya kualitasnya tetap prima.",
      },
    ],
  },

  location: {
    title: "Mampir ke Syakilla Juice",
    intro:
      "Ada di kawasan Batuphat Timur, Lhokseumawe. Mampir langsung atau pesan online buat diantar ke sekitar sini.",
    address:
      "Jl. Medan - Banda Aceh, Batuphat Timur, Kec. Muara Satu, Kota Lhokseumawe, Aceh 24352",
    hours: "Buka setiap hari, 09.00 - 22.00 WIB",
    phone: "+62 857-6225-8302",
    mapsUrl: "https://maps.app.goo.gl/RJr5J68jmENx1cq2A",
    mapEmbed:
      "https://www.google.com/maps?q=Batuphat+Timur+Lhokseumawe+Aceh&output=embed",
  },

  cart: {
    currencyPrefix: "Rp ",
    currencyLocale: "id-ID",
    whatsappNumber: "6285762258302",
    waIntro: "Halo Syakilla Juice! Saya mau pesan:",
  },
};

export default SITE;